/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j_extensions_comm_SerialComm */

#ifndef _Included_j_extensions_comm_SerialComm
#define _Included_j_extensions_comm_SerialComm
#ifdef __cplusplus
extern "C" {
#endif
#undef j_extensions_comm_SerialComm_NO_PARITY
#define j_extensions_comm_SerialComm_NO_PARITY 0L
#undef j_extensions_comm_SerialComm_ODD_PARITY
#define j_extensions_comm_SerialComm_ODD_PARITY 1L
#undef j_extensions_comm_SerialComm_EVEN_PARITY
#define j_extensions_comm_SerialComm_EVEN_PARITY 2L
#undef j_extensions_comm_SerialComm_MARK_PARITY
#define j_extensions_comm_SerialComm_MARK_PARITY 3L
#undef j_extensions_comm_SerialComm_SPACE_PARITY
#define j_extensions_comm_SerialComm_SPACE_PARITY 4L
#undef j_extensions_comm_SerialComm_ONE_SB
#define j_extensions_comm_SerialComm_ONE_SB 1L
#undef j_extensions_comm_SerialComm_ONE_POINT_FIVE_SB
#define j_extensions_comm_SerialComm_ONE_POINT_FIVE_SB 2L
#undef j_extensions_comm_SerialComm_TWO_SB
#define j_extensions_comm_SerialComm_TWO_SB 3L
/*
 * Class:     j_extensions_comm_SerialComm
 * Method:    getCommPorts
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_j_extensions_comm_SerialComm_getCommPorts
  (JNIEnv *, jclass);

/*
 * Class:     j_extensions_comm_SerialComm
 * Method:    openPort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_j_extensions_comm_SerialComm_openPort
  (JNIEnv *, jobject);

/*
 * Class:     j_extensions_comm_SerialComm
 * Method:    closePort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_j_extensions_comm_SerialComm_closePort
  (JNIEnv *, jobject);

/*
 * Class:     j_extensions_comm_SerialComm
 * Method:    configPort
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_j_extensions_comm_SerialComm_configPort
  (JNIEnv *, jobject);

/*
 * Class:     j_extensions_comm_SerialComm
 * Method:    readBytes
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_j_extensions_comm_SerialComm_readBytes
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     j_extensions_comm_SerialComm
 * Method:    writeBytes
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_j_extensions_comm_SerialComm_writeBytes
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
